export const PORTABLE_INTERACTIVE_MODULE_ORDER = [
  "observability",
  "path",
  "safety-shims",
  "macports",
  "homebrew",
  "bun",
  "nvm",
  "rust",
  "android",
  "runtime-paths",
  "completion-directories",
  "oh-my-zsh",
  "completion",
  "prompt-vi",
  "aliases",
  "search",
  "history",
  "dburl",
  "ports-manager",
  "private",
] as const;

export const PORTABLE_LOGIN_MODULE_ORDER = [
  "observability",
  "path",
  "safety-shims",
  "macports",
  "homebrew",
  "bun",
  "rust",
  "android",
  "runtime-paths",
] as const;
